environment:
  TWINE_USERNAME: __token__
  global:
    CIBW_BUILD: cp3[78]-*
    CIBW_SKIP: "*-win32 *-manylinux_i686"
    CIBW_BEFORE_BUILD: "python -m pip install --upgrade pip && python -m pip install -r requirements.txt"

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      APPVEYOR_JOB_NAME: "python38-x64-macos"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      APPVEYOR_JOB_NAME: "python38-x64-vs2019"
      PYTHON: "C:\\Python38-x64"
      PYTHON_ARCH: "64"

stack: python 3.8

init:
  - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - python -m pip install --upgrade pip
  - python -m pip install cibuildwheel==1.6.0

build_script:
  - python -m cibuildwheel --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        python -m pip install twine
        python -m twine upload wheelhouse/*.whl
      }

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
